Repository Daniel-dadu/PAE_web_platform, pull requests merged in 2022-06, with the labels that each got.

#295 View registro asesor tmp
  frontend/src/components/reusable/CalendarioDisponibilidad/CalendarioDisponibilidad.jsx
  frontend/src/components/reusable/CampoSeleccionarEnListaDesplegable/CampoSeleccionarEnListaDesplegable.jsx
  frontend/src/components/reusable/ImagenPerfilActualizar/ImagenPerfilActualizar.jsx
  frontend/src/components/reusable/ListaDesplegable/ListaDesplegable.jsx
  frontend/src/components/reusable/ListaUsuarios/ListaUsuarios.jsx
  frontend/src/components/reusable/PopUpEncuesta/PopUpEncuesta.jsx
  frontend/src/components/reusable/PopUpGeneral/PopUpGeneral.jsx
  frontend/src/components/reusable/TarjetaListaDesplegable/TarjetaListaDesplegable.jsx
  frontend/src/routeIndex.js
  frontend/src/views/LandingPage/LandingPage.jsx
  frontend/src/views/TemplateRegistroUsuario/TemplateRegistroUsuario.jsx
  frontend/src/views/asesor/registroAsesorDatos/RegistroAsesorDatos.css
  frontend/src/views/asesor/registroAsesorDatos/RegistroAsesorDatos.jsx
  frontend/src/views/asesor/registroAsesorDatos/info.json
  frontend/src/views/asesor/registroAsesorHorario/RegistroAsesorHorario.jsx
  frontend/src/views/asesor/registroAsesorHorario/registroAsesorHorario.css
  frontend/src/views/asesor/registroAsesorUF/RegistroAsesorUF.css
  frontend/src/views/asesor/registroAsesorUF/RegistroAsesorUF.jsx
  frontend/src/views/componentPreview/DanielFlores/DanielFlores.jsx
Labels: coding, backend

#296 Fixes danoman
  frontend/src/components/reusable/ListaDesplegable/ListaDesplegable.jsx
  frontend/src/components/reusable/ListaDesplegable/data.json
  frontend/src/components/reusable/ListaDesplegable/listaDesplegable.css
  frontend/src/components/reusable/PopUpSolicitudAsesoria/PopUpSolicitudAsesoria.jsx
  frontend/src/components/reusable/TarjetaListaDesplegable/TarjetaListaDesplegable.jsx
  frontend/src/components/reusable/TarjetaListaDesplegable/tarjetaListaDesplegable.css
  frontend/src/routeIndex.js
  frontend/src/views/componentPreview/DanielFlores/DanielFlores.jsx
Labels: coding

#298 Registro asesor connected to backend
  backend/microservices/General/General.js
  backend/microservices/General/queries.js
  backend/microservices/Registro/Registro.js
  backend/microservices/Registro/queries.js
  frontend/src/components/reusable/CalendarioDisponibilidad/CalendarioDisponibilidad.jsx
  frontend/src/components/reusable/CalendarioDisponibilidad/PruebaCalendarioDisponibilidad.json
  frontend/src/components/reusable/ListaDesplegable/ListaDesplegable.jsx
  frontend/src/components/reusable/ListaDesplegable/listaDesplegable.css
  frontend/src/components/reusable/ListaUnidadesDeFormacionAsesor/ListaUnidadesDeFormacionAsesor.jsx
  frontend/src/components/reusable/ListaUnidadesDeFormacionAsesor/listaUnidadesDeFormacionAsesor.css
  frontend/src/components/reusable/TarjetaListaDesplegable/TarjetaListaDesplegable.jsx
  frontend/src/components/reusable/TarjetaListaDesplegable/tarjetaListaDesplegable.css
  frontend/src/views/TemplateRegistroUsuario/TemplateRegistroUsuario.jsx
  frontend/src/views/asesor/registroAsesorCondiciones/RegistroAsesorCondiciones.css
  frontend/src/views/asesor/registroAsesorCondiciones/RegistroAsesorCondiciones.jsx
  frontend/src/views/asesor/registroAsesorCondiciones/condiciones.json
  frontend/src/views/asesor/registroAsesorDatos/RegistroAsesorDatos.jsx
  frontend/src/views/asesor/registroAsesorHorario/RegistroAsesorHorario.jsx
  frontend/src/views/asesor/registroAsesorResumen/RegistroAsesorResumen.css
  frontend/src/views/asesor/registroAsesorResumen/RegistroAsesorResumen.jsx
  frontend/src/views/asesor/registroAsesorUF/PruebaRegistroAsesorUF.json
  frontend/src/views/asesor/registroAsesorUF/RegistroAsesorUF.css
  frontend/src/views/asesor/registroAsesorUF/RegistroAsesorUF.jsx
  frontend/src/views/asesorado/registroAsesoradoCondiciones/RegistroAsesoradoCondiciones.jsx
  frontend/src/views/asesorado/registroAsesoradoDatos/RegistroAsesoradoDatos.jsx
  frontend/src/views/asesorado/registroAsesoradoResumen/RegistroAsesoradoResumen.jsx
Labels: coding, backend

#306 Responsive danoman
  frontend/src/components/reusable/BarraLateral/BarraLateral.css
  frontend/src/components/reusable/BarraLateral/BarraLateral.jsx
  frontend/src/components/reusable/TarjetaMaestra/TarjetaMaestra.css
  frontend/src/components/reusable/TarjetaMaestra/TarjetaMaestra.jsx
  frontend/src/views/Template/Template.css
  frontend/src/views/Template/Template.jsx
  frontend/src/views/componentPreview/DanielFlores/DanielFlores.jsx
Labels: design, coding

#307 Administrar (y un par de cosas más) conectadas al back end
  backend/microservices/Administracion/Administracion.js
  backend/microservices/Administracion/queries.js
  backend/microservices/Asesoria/Asesoria.js
  backend/microservices/Encuesta/.gitignore
  backend/microservices/Encuesta/Encuesta.js
  backend/microservices/Encuesta/package-lock.json
  backend/microservices/Encuesta/package.json
  backend/microservices/Encuesta/queries.js
  backend/microservices/Login/Login.js
  backend/microservices/Login/queries.js
  backend/microservices/Perfil/Perfil.js
  backend/microservices/Perfil/queries.js
  backend/microservices/Registro/Registro.js
  backend/microservices/Registro/queries.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/noImage.png
  frontend/src/components/reusable/BarraLateral/BarraLateral.jsx
  frontend/src/components/reusable/ImagenPerfilCambiar/ImagenPerfilCambiar.css
  frontend/src/components/reusable/ImagenPerfilCambiar/ImagenPerfilCambiar.jsx
  frontend/src/components/reusable/ListaDesplegable/ListaDesplegable.jsx
  frontend/src/components/reusable/ListaUsuarios/ListaUsuarios.jsx
  frontend/src/components/reusable/ListaUsuarios/listaUsuarios.css
  frontend/src/components/reusable/PopUpEncuesta/PopUpEncuesta.jsx
  frontend/src/components/reusable/PopUpEncuesta/popUpEncuesta.css
  frontend/src/components/reusable/PopUpInformacionAsesoria/Portal.js
  frontend/src/components/reusable/PreguntaAbiertaEncuesta/PreguntaAbiertaEncuesta.jsx
  frontend/src/components/reusable/PreguntaCerradaEncuesta/PreguntaCerradaEncuesta.css
  frontend/src/components/reusable/PreguntaCerradaEncuesta/PreguntaCerradaEncuesta.jsx
  frontend/src/components/reusable/TarjetaListaDesplegable/TarjetaListaDesplegable.jsx
  frontend/src/hooks/useScript.js
  frontend/src/routeIndex.js
  frontend/src/views/LandingPage/Login.js
  frontend/src/views/LandingPage/login.css
  frontend/src/views/LandingPage/recuperarPassword/RecuperarPassword.js
  frontend/src/views/LandingPage/recuperarPassword/RecuperarPassword.jsx
  frontend/src/views/LandingPage/reestrablecerPassword/ReestrablecerPassword.js
  frontend/src/views/LandingPage/reestrablecerPassword/ReestrablecerPassword.jsx
  frontend/src/views/asesor/perfil/PerfilAsesor.jsx
  frontend/src/views/asesorado/perfil/PerfilAsesorado.jsx
  frontend/src/views/asesorado/registroAsesoradoDatos/RegistroAsesoradoDatos.jsx
  frontend/src/views/commons/administrarUsuariosDirectivos/AdministrarUsuariosDirectivos.css
  frontend/src/views/commons/administrarUsuariosDirectivos/AdministrarUsuariosDirectivos.jsx
  frontend/src/views/commons/respuestasEncuestas/PruebaRespuestasEncuestas.json
  frontend/src/views/commons/respuestasEncuestas/RespuestasEncuestas.css
  frontend/src/views/commons/respuestasEncuestas/RespuestasEncuestas.jsx
  frontend/src/views/componentPreview/DanielMaldonado/DanielMaldonado.css
  frontend/src/views/componentPreview/DanielMaldonado/DanielMaldonado.jsx
  frontend/src/views/componentPreview/DanielMunive/DanielMunive.jsx
  frontend/src/views/directivo/administrarPerfil/AdministrarPerfil.css
  frontend/src/views/directivo/administrarPerfil/AdministrarPerfil.jsx
  frontend/src/views/directivo/administrarPeriodo/AdministrarPeriodo.css
  frontend/src/views/directivo/administrarPeriodo/AdministrarPeriodo.jsx
  frontend/src/views/directivo/administrarUsuario/AdministrarUsuarios.css
  frontend/src/views/directivo/administrarUsuario/AdministrarUsuarios.jsx
  frontend/src/views/directivo/administrarUsuario/imagesAdministra/management.png
  frontend/src/views/directivo/administrarUsuario/imagesAdministra/schedule.png
  frontend/src/views/directivo/registroDirectivo/RegistroDirectivo.css
  frontend/src/views/directivo/registroDirectivo/RegistroDirectivo.jsx
Labels: coding, backend
