Repository Daniel-dadu/PAE_web_platform, pull requests merged in 2022-05, with the labels that each got.

#147 View agendar asesoria duda #31
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/reusable/BotonConImagen/BotonConImagen.jsx
  frontend/src/components/reusable/CampoTextoGrande/CampoTextoGrande.jsx
  frontend/src/components/reusable/ImagenAsesoria/ImagenAsesoria.jsx
  frontend/src/routeIndex.js
  frontend/src/views/asesorado/agendarAsesoriaDuda/AgendarAsesoriaDuda.css
  frontend/src/views/asesorado/agendarAsesoriaDuda/AgendarAsesoriaDuda.jsx
  frontend/src/views/componentPreview/TemporalHome/TemporalHome.jsx
Labels: coding

#148 Login interfaz terminada #11
  frontend/public/index.html
  frontend/src/routeIndex.js
  frontend/src/views/LandingPage/LandingPage.js
  frontend/src/views/LandingPage/Login.js
  frontend/src/views/LandingPage/login.css
Labels: coding

#149 View Login/LandingPage #85
  frontend/public/index.html
  frontend/src/views/LandingPage/LandingPage.js
  frontend/src/views/LandingPage/Login.js
  frontend/src/views/LandingPage/landingPage.css
  frontend/src/views/LandingPage/login.css
Labels: coding

#150 Hotfix daniel maldonado
  frontend/src/components/reusable/BarraLateral/API.json
  frontend/src/components/reusable/BarraLateral/BarraLateral.jsx
  frontend/src/components/reusable/BarraLateral/btnInfo.js
  frontend/src/views/Template/Template.css
  frontend/src/views/Template/Template.jsx
  frontend/src/views/commons/agendarAsesoria/AgendarAsesoria.jsx
  frontend/src/views/componentPreview/DanielMaldonado/DanielMaldonado.css
  frontend/src/views/componentPreview/DanielMaldonado/DanielMaldonado.jsx
Labels: bug, coding

#156 Hotfix set buttons
  frontend/src/components/reusable/BarraLateral/BarraLateral.jsx
  frontend/src/views/asesorado/agendarAsesoriaDuda/AgendarAsesoriaDuda.css
  frontend/src/views/asesorado/agendarAsesoriaDuda/AgendarAsesoriaDuda.jsx
  frontend/src/views/asesorado/agendarAsesoriaUF/AgendarAsesoriaUF.jsx
  frontend/src/views/commons/agendarAsesoria/AgendarAsesoria.jsx
Labels: bug, coding

#210 Microservice asesoria
  backend/microservices/Asesoria/.gitignore
  backend/microservices/Asesoria/Asesoria.js
  backend/microservices/Asesoria/queries.js
Labels: coding, backend

#214 Microservice login
  backend/microservices/EncryptionFile/encrypt.js
  backend/microservices/Login/.gitignore
  backend/microservices/Login/Login.js
  backend/microservices/Login/package-lock.json
  backend/microservices/Login/package.json
  backend/microservices/Login/queries.js
Labels: coding, backend

#217 View recuperar contrasenia #163
  .gitignore
  frontend/src/assets/recuperarPassword.png
  frontend/src/routeIndex.js
  frontend/src/views/LandingPage/recuperarPassword/RecuperarPassword.js
  frontend/src/views/LandingPage/recuperarPassword/recuperarPassword.css
Labels: coding

#219 Microservice asesoria
  backend/microservices/Asesoria/Asesoria.js
  backend/microservices/Asesoria/package-lock.json
  backend/microservices/Asesoria/package.json
  backend/microservices/Asesoria/queries.js
Labels: coding, backend

#220 finished view-ReestablecerContrasenia #164
  frontend/src/assets/reestablecerPassword.png
  frontend/src/routeIndex.js
  frontend/src/views/LandingPage/LandingPage.jsx
  frontend/src/views/LandingPage/reestrablecerPassword/ReestrablecerPassword.js
  frontend/src/views/LandingPage/reestrablecerPassword/reestablecerPassword.css
Labels: coding

#222 Revert "Finished view-LoginDirectivo #167"
  frontend/src/routeIndex.js
  frontend/src/views/LandingPage/Login.js
  frontend/src/views/directivo/Login/LoginDirectivo.js
  frontend/src/views/directivo/Login/loginDirectivo.css
Labels: coding

#243 View login directivo
  frontend/src/routeIndex.js
  frontend/src/views/LandingPage/Login.js
  frontend/src/views/LandingPage/login.css
  frontend/src/views/directivo/Login/LoginDirectivo.js
  frontend/src/views/directivo/Login/loginDirectivo.css
Labels: coding

#246 Componente lista usuarios #181
  frontend/src/components/reusable/ListaUsuarios/ListaUsuarios.js
  frontend/src/components/reusable/ListaUsuarios/listaUsuarios.css
  frontend/src/components/reusable/ListaUsuarios/pruebaListaUsuarios.json
  frontend/src/routeIndex.js
Labels: coding

#249 Componente pop up general #182
  frontend/src/components/reusable/PopUpGeneral/PopUpGeneral.js
  frontend/src/components/reusable/PopUpGeneral/popUpGeneral.css
  frontend/src/routeIndex.js
  frontend/src/views/componentPreview/DanielFlores/DanielFlores.js
Labels: coding

#252 Componente informacion personal usuario
  frontend/src/assets/img-editar-perfil-tmp.JPG
  frontend/src/components/reusable/CampoTextoPequeno/CampoTextoPequeno.jsx
  frontend/src/components/reusable/ImagenPerfilActualizar/ImagenPerfilActualizar.css
  frontend/src/components/reusable/ImagenPerfilActualizar/ImagenPerfilActualizar.js
  frontend/src/components/reusable/InformacionPersonalUsuario/InformacionPersonalUsuario.js
  frontend/src/components/reusable/InformacionPersonalUsuario/data.json
  frontend/src/components/reusable/InformacionPersonalUsuario/informacionPersonalUsuario.css
  frontend/src/components/reusable/PopUpGeneral/PopUpGeneral.js
  frontend/src/routeIndex.js
  frontend/src/views/componentPreview/DanielFlores/DanielFlores.js
  frontend/src/views/componentPreview/DanielFlores/danielFlores.css
Labels: coding

#253 finished component #177
  frontend/src/components/reusable/TarjetaListaDesplegable/TarjetaListaDesplegable.js
  frontend/src/components/reusable/TarjetaListaDesplegable/tarjetaListaDesplegable.css
  frontend/src/routeIndex.js
  frontend/src/views/componentPreview/DanielFlores/DanielFlores.js
Labels: coding

#254 Finished component #176
  frontend/src/components/reusable/BarraLateral/BarraLateral.jsx
  frontend/src/components/reusable/ListaDesplegable/ListaDesplegable.js
  frontend/src/components/reusable/ListaDesplegable/data.json
  frontend/src/components/reusable/ListaDesplegable/listaDesplegable.css
  frontend/src/components/reusable/TarjetaListaDesplegable/TarjetaListaDesplegable.js
  frontend/src/components/reusable/TarjetaListaDesplegable/tarjetaListaDesplegable.css
  frontend/src/routeIndex.js
  frontend/src/views/componentPreview/DanielFlores/DanielFlores.js
Labels: coding

#257 Componente cambio mes periodo to develop
  frontend/src/assets/reusableFunctions/dateFunctions.js
  frontend/src/components/reusable/CambioMesPeriodo/CambioMesPeriodo.jsx
  frontend/src/views/commons/calendario/Calendario.jsx
Labels: coding

#258 componente terminado #169
  frontend/src/components/reusable/ListaUnidadesDeFormacionAsesor/ListaUnidadesDeFormacionAsesor.js
  frontend/src/components/reusable/ListaUnidadesDeFormacionAsesor/listaUnidadesDeFormacionAsesor.css
  frontend/src/components/reusable/TarjetaListaDesplegable/TarjetaListaDesplegable.js
  frontend/src/components/reusable/TarjetaListaDesplegable/tarjetaListaDesplegable.css
  frontend/src/routeIndex.js
  frontend/src/views/asesorado/registroAsesoradoResumen/RegistroAsesoradoResumen.js
  frontend/src/views/componentPreview/DanielFlores/DanielFlores.js
  frontend/src/views/useIsOverflowX.js
Labels: coding

#267 registro asesorado conectado con backend
  backend/database/databaseArchitecture.sql
  backend/microservices/Registro/Registro.js
  backend/microservices/Registro/queries.js
  frontend/src/App.jsx
  frontend/src/components/reusable/BarraLateral/BarraLateral.css
  frontend/src/components/reusable/BarraLateral/BarraLateral.jsx
  frontend/src/components/reusable/CampoTextoPequeno/CampoTextoPequeno.css
  frontend/src/components/reusable/CampoTextoPequeno/CampoTextoPequeno.jsx
  frontend/src/components/reusable/ImagenPerfilCambiar/ImagenPerfilCambiar.css
  frontend/src/components/reusable/ImagenPerfilCambiar/ImagenPerfilCambiar.jsx
  frontend/src/components/reusable/TarjetaMaestra/TarjetaMaestra.jsx
  frontend/src/routeIndex.js
  frontend/src/views/LandingPage/Login.js
  frontend/src/views/LandingPage/login.css
  frontend/src/views/TemplateRegistroUsuario/TemplateRegistroUsuario.css
  frontend/src/views/TemplateRegistroUsuario/TemplateRegistroUsuario.jsx
  frontend/src/views/asesorado/registroAsesoradoCondiciones/RegistroAsesoradoCondiciones.css
  frontend/src/views/asesorado/registroAsesoradoCondiciones/RegistroAsesoradoCondiciones.jsx
  frontend/src/views/asesorado/registroAsesoradoCondiciones/condiciones.json
  frontend/src/views/asesorado/registroAsesoradoDatos/RegistroAsesoradoDatos.css
  frontend/src/views/asesorado/registroAsesoradoDatos/RegistroAsesoradoDatos.jsx
  frontend/src/views/asesorado/registroAsesoradoDatos/info.json
  frontend/src/views/asesorado/registroAsesoradoResumen/RegistroAsesoradoResumen.js
  frontend/src/views/asesorado/registroAsesoradoResumen/RegistroAsesoradoResumen.jsx
  frontend/src/views/asesorado/registroAsesoradoResumen/data.json
  frontend/src/views/commons/agendarAsesoria/AgendarAsesoria.jsx
  frontend/src/views/componentPreview/TemporalHome/TemporalHome.jsx
Labels: coding, backend

#270 View registro asesor horario
  frontend/src/App.jsx
  frontend/src/components/reusable/PopUpEncuesta/PopUpEncuesta.js
  frontend/src/routeIndex.js
  frontend/src/views/asesor/registroAsesorHorario/RegistroAsesorHorario.jsx
  frontend/src/views/asesor/registroAsesorHorario/registroAsesorHorario.css
Labels: coding

#273 View administrar perfil asesor directivos
  frontend/src/App.jsx
  frontend/src/components/reusable/ListaUsuarios/ListaUsuarios.js
  frontend/src/components/reusable/PopUpGeneral/PopUpGeneral.js
  frontend/src/components/reusable/PopUpGeneral/popUpGeneral.css
  frontend/src/routeIndex.js
  frontend/src/views/componentPreview/DanielFlores/DanielFlores.js
  frontend/src/views/directivo/administrarPerfilAsesorDirectivos/AdministrarPerfilAsesorDirectivos.jsx
  frontend/src/views/directivo/administrarPerfilAsesorDirectivos/administrarPerfilAsesorDirectivos.css
  frontend/src/views/directivo/administrarPerfilAsesoradoDirectivos/administrarPerfilAsesoradoDirectivos.jsx
Labels: coding

#277 View perfil asesorado
  frontend/src/views/asesorado/perfil/PerfilAsesorado.jsx
  frontend/src/views/asesorado/perfil/perfilAsesorado.css
  frontend/src/views/asesorado/perfil/placeholder
Labels: coding

#280 Finish view-EnviarNotificacionDirectivos #205
  frontend/src/routeIndex.js
  frontend/src/views/directivo/enviarNotificacionDirectivos/EnviarNotificacionDirectivos.jsx
  frontend/src/views/directivo/enviarNotificacionDirectivos/enviarNotificacionesDirectivos.css
Labels: coding

#283 Improved Style of component adding overflow
  frontend/src/components/reusable/CalendarioMini/CalendarioMini.jsx
  frontend/src/components/reusable/CampoSeleccionarEnListaDesplegable/CampoSeleccionarEnListaDesplegable.jsx
  frontend/src/views/asesorado/AgendarAsesoriaResumen/AgendarAsesoriaResumen.jsx
  frontend/src/views/asesorado/agendarAsesoriaDuda/AgendarAsesoriaDuda.jsx
  frontend/src/views/asesorado/agendarAsesoriaHora/AgendarAsesoriaHora.jsx
  frontend/src/views/asesorado/agendarAsesoriaUF/AgendarAsesoriaUF.jsx
  frontend/src/views/asesorado/registroAsesoradoCondiciones/RegistroAsesoradoCondiciones.jsx
  frontend/src/views/asesorado/registroAsesoradoDatos/RegistroAsesoradoDatos.jsx
  frontend/src/views/asesorado/registroAsesoradoResumen/RegistroAsesoradoResumen.jsx
Labels: coding, backend

#287 Componente pop up solicitud asesoria
  frontend/src/components/reusable/ListaDesplegable/ListaDesplegable.js
  frontend/src/components/reusable/PopUpSolicitudAsesoria/PopUpSolicitudAsesoria.jsx
  frontend/src/components/reusable/PopUpSolicitudAsesoria/popUpSolicitudAsesoria.css
  frontend/src/routeIndex.js
  frontend/src/views/componentPreview/DanielFlores/DanielFlores.js
Labels: coding

#291 Componente campo seleccionar en lista desplegable with backend
  backend/microservices/Asesoria/queries.js
  frontend/src/components/reusable/CampoSeleccionarEnListaDesplegable/CampoSeleccionarEnListaDesplegable.css
  frontend/src/components/reusable/CampoSeleccionarEnListaDesplegable/CampoSeleccionarEnListaDesplegable.jsx
  frontend/src/components/reusable/InformacionPersonalUsuario/InformacionPersonalUsuario.jsx
  frontend/src/components/reusable/placeholder
  frontend/src/views/asesorado/agendarAsesoriaUF/AgendarAsesoriaUF.css
  frontend/src/views/asesorado/agendarAsesoriaUF/AgendarAsesoriaUF.jsx
  frontend/src/views/asesorado/registroAsesoradoDatos/RegistroAsesoradoDatos.jsx
  frontend/src/views/commons/agendarAsesoria/AgendarAsesoria.jsx
Labels: coding
